### ISSUE TITLE
Check crashing wrt pddl lib

### ISSUE THREAD

**Issue by ssardina** [AI-Planning/fond-utils#3]
Hi @haz 

Sorry I just managed to get to this, and I am about to go for summer holidays... :sunglasses: 

I kind of forgot where we were in this repo, but if I remember well we both started to do lifted determinization and here you have integrated parts of my [fond2allout](https://github.com/ssardina-research/fond2allout) repo here, including extensions to the pddl lib. All good.

I just did a cold check and.... 

```shell
$ python -m fondutils check --input tests/domain_03.pddl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ssardina/PROJECTS/planning/FOND/parsers/fond-utils.git/fondutils/__main__.py", line 6, in <module>
    from fondutils.normalizer import normalize
  File "/home/ssardina/PROJECTS/planning/FOND/parsers/fond-utils.git/fondutils/normalizer.py", line 5, in <module>
    from pddl.logic.effects import When, AndEffect
ImportError: cannot import name 'AndEffect' from 'pddl.logic.effects' (/home/ssardina/opt/virtual-envs/p12/lib/python3.12/site-packages/pddl/logic/effects.py). Did you mean: 'CondEffect'?
```

**Comment by ssardina** [comment]
This is also crashing in my fond2allout repo, so I suspect something must have changed in the pddl library...

**Comment by ssardina** [comment]
OK correct, pddl has changed from:

```python
Effect = Union[AndEffect["CEffect"], CEffect]
```

with `AndEffect` having its own class, to directly use the `And` base class:

```python
Effect = Union[And, CEffect]
```

Will try to fix this now..

**Comment by ssardina** [comment]
OK this `AndEffect` has been fixed, but I wonder if other change in the pddl library would have an impact here (determinizer or normalizer. The new effects are:

```python
PEffect = Union[Atomic, Not]
CEffect = Union[Forall, When, OneOf, "PEffect"]
Effect = Union[And, CEffect]
CondEffect = Union[And, "PEffect"]
```


Whereas the [old effects](https://github.com/AI-Planning/pddl/blob/v0.3.1/pddl/logic/effects.py) (when this repo was programmed) was:

```python
PEffect = Union[Atomic, Not]
CEffect = Union[Forall, When, OneOf, "PEffect"]
Effect = Union[AndEffect["CEffect"], CEffect]
CondEffect = Union[AndEffect["PEffect"], "PEffect"]
```
I think fixing the `AndEffect` (to simply `And`) may be enough, but not 100% sure...

**Comment by ssardina** [comment]
OK a few things fixed and optimised, but it crashes when normalizing:

![image](https://github.com/user-attachments/assets/9c9c3125-779b-4ebb-8c64-ea05174baba1)


I think the `And([])` should now be `And()`, an and with empty predicates (true!)

**Comment by ssardina** [comment]
I think this all has been resolved now.
